#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
visualise.py — render LOBSTER depth heatmaps and compute SSIM / KL / temporal-corr / latent-distance
for real vs synthetic sequences generated by a trained TimeGAN model.

Consumes CLI via the unified Options() router with a `--viz …` section:

    python -m src.viz.visualise \
      --viz --samples 5 --out-dir ./outs/viz_run1 --cmap magma --dpi 240 --bins 128 --levels 10 \
      --dataset --seq-len 128 --data-dir ./data \
                --orderbook-filename AMZN_2012-06-21_34200000_57600000_orderbook_10.csv \
      --modules --batch-size 128 --z-dim 40 --hidden-dim 64 --num-layer 3 --num-iters 25000
"""

from __future__ import annotations

from pathlib import Path
from typing import List, Tuple

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from numpy.typing import NDArray

from src.dataset import load_data
from src.helpers.args import Options
from src.helpers.constants import NUM_LEVELS as DEFAULT_LEVELS
from src.helpers.constants import OUTPUT_DIR
from src.helpers.richie import log as rlog
from src.helpers.richie import rule as rrule
from src.helpers.richie import status as rstatus
from src.helpers.utils import (
    get_kl_metrics,
    get_ssim,
    latent_divergence,
    temporal_consistency,
)
from src.modules import TimeGAN

# Optional pretty tables (graceful fallback if rich unavailable)
try:
    from rich import box
    from rich.console import Console
    from rich.table import Table

    _HAS_RICH = True
except ImportError:
    _HAS_RICH = False


# --------------------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------------------
def _pick_cmap(name: str):
    """Resolve a matplotlib colormap by name with fallback."""
    try:
        return plt.get_cmap(name)
    except Exception:
        rlog(f"[warn] unknown colormap '{name}', falling back to 'coolwarm'")
        return plt.get_cmap("coolwarm")


def plot_heatmap(
    data_2d: NDArray,
    *,
    lvls: int,
    c_map: str,
    used_log1p: bool,
    title: str,
    save_path: Path,
    dpint: int,
) -> None:
    """
    Render a single heatmap with asks stacked above bids.
    Rows = 2*levels (top half: ask sizes 1…L, bottom half: bid sizes 1…L), columns = time.
    """
    # Extract per-level sizes from [ask_p, ask_sz, bid_p, bid_sz] repeating by level
    asks = np.stack([data_2d[:, 4 * L + 1] for L in range(lvls)], axis=1)  # [T, L]
    bids = np.stack([data_2d[:, 4 * L + 3] for L in range(lvls)], axis=1)  # [T, L]

    mat = np.concatenate([asks.T, bids.T], axis=0)  # [2L, T]
    if used_log1p:
        mat = np.log1p(mat)  # compress dynamic range for visualization

    sns.set_theme(style="whitegrid")
    fig, ax = plt.subplots(figsize=(9, 6))
    sns.heatmap(mat, ax=ax, cmap=_pick_cmap(c_map), cbar=True)
    ax.set_title(title)
    ax.set_ylabel("Levels (Top = Ask, Bottom = Bid)")
    ax.set_xlabel("Time")
    fig.tight_layout()

    save_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(save_path, dpi=dpint, bbox_inches="tight")
    plt.close(fig)
    rlog(f"[save] heatmap → {save_path}")


# --------------------------------------------------------------------------------------
# Metrics presentation
# --------------------------------------------------------------------------------------
def _print_metrics_table(
    ssimi_rows: List[Tuple[str, float]],
    kla_rows: List[Tuple[str, float, float]],
    tmp_rows: List[Tuple[str, float]],
    late_rows: List[Tuple[str, float]],
) -> None:
    """Pretty-print metrics (SSIM, KL(spread/mpr), temporal corr, latent distance)."""
    if not ssimi_rows:
        rlog("[info] no metrics to display")
        return

    if not _HAS_RICH:
        for j in range(len(ssimi_rows)):
            rlog(
                f"{ssimi_rows[j][0]} | "
                f"SSIM={ssimi_rows[j][1]:.4f} | "
                f"KL(sp)={kla_rows[j][1]:.4f} | KL(mpr)={kla_rows[j][2]:.4f} | "
                f"TempCorr={tmp_rows[j][1]:.4f} | LatDist={late_rows[j][1]:.4f}"
            )
        return

    table = Table(
        title="Quantitative Metrics",
        header_style="bold cyan",
        box=box.SIMPLE_HEAVY,
        show_lines=False,
    )
    table.add_column("Sample")
    table.add_column("SSIM", justify="right")
    table.add_column("KL(spread)", justify="right")
    table.add_column("KL(mpr)", justify="right")
    table.add_column("TempCorr", justify="right")
    table.add_column("LatDist", justify="right")

    for j in range(len(ssimi_rows)):
        table.add_row(
            ssimi_rows[j][0],
            f"{ssimi_rows[j][1]:.4f}",
            f"{kla_rows[j][1]:.4f}",
            f"{kla_rows[j][2]:.4f}",
            f"{tmp_rows[j][1]:.4f}",
            f"{late_rows[j][1]:.4f}",
        )

    rrule()
    try:
        Console().print(table)
    except Exception:
        for j in range(len(ssimi_rows)):
            rlog(
                f"{ssimi_rows[j][0]} | "
                f"SSIM={ssimi_rows[j][1]:.4f} | "
                f"KL(sp)={kla_rows[j][1]:.4f} | KL(mpr)={kla_rows[j][2]:.4f} | "
                f"TempCorr={tmp_rows[j][1]:.4f} | LatDist={late_rows[j][1]:.4f}"
            )
    rrule()


def _maybe_write_metrics_csv(
    out_csv: Path | None,
    ssimi_rows: List[Tuple[str, float]],
    kla_rows: List[Tuple[str, float, float]],
    tmp_rows: List[Tuple[str, float]],
    late_rows: List[Tuple[str, float]],
) -> None:
    """Optionally write a CSV with all computed metrics."""
    if not out_csv:
        return
    import csv

    out_csv.parent.mkdir(parents=True, exist_ok=True)
    with out_csv.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["sample", "ssim", "kl_spread", "kl_mpr", "temp_corr", "lat_dist"])
        for j in range(len(ssimi_rows)):
            w.writerow(
                [
                    ssimi_rows[j][0],
                    f"{ssimi_rows[j][1]:.6f}",
                    f"{kla_rows[j][1]:.6f}",
                    f"{kla_rows[j][2]:.6f}",
                    f"{tmp_rows[j][1]:.6f}",
                    f"{late_rows[j][1]:.6f}",
                ]
            )
    rlog(f"[save] metrics CSV → {out_csv}")


# --------------------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------------------
if __name__ == "__main__":
    rrule("[bold cyan]Heatmaps, SSIM, KL, Temporal Corr, Latent Distance[/bold cyan]")

    # Parse unified options: top-level + nested {dataset, modules, viz}
    opts = Options().parse()
    ds = opts.dataset
    mod = opts.modules
    viz = getattr(opts, "viz", None)

    # Visualization defaults if section was omitted
    samples: int = max(0, getattr(viz, "samples", 3) if viz else 3)
    out_dir: Path = (
        getattr(viz, "out_dir", Path(OUTPUT_DIR) / "viz")
        if viz
        else (Path(OUTPUT_DIR) / "viz")
    )
    bins: int = getattr(viz, "bins", 100) if viz else 100
    cmap: str = getattr(viz, "cmap", "coolwarm") if viz else "coolwarm"
    use_log1p: bool = not getattr(viz, "no_log1p", False) if viz else True
    dpi: int = getattr(viz, "dpi", 220) if viz else 220
    levels: int = (
        int(getattr(viz, "levels"))
        if (viz and getattr(viz, "levels", None) is not None)
        else int(DEFAULT_LEVELS)
    )
    do_ssim: bool = not getattr(viz, "no_ssim", False) if viz else True
    do_kl: bool = not getattr(viz, "no_kl", False) if viz else True
    do_temp: bool = not getattr(viz, "no_temp", False) if viz else True
    do_lat: bool = not getattr(viz, "no_lat", False) if viz else True
    metrics_csv: Path | None = getattr(viz, "metrics_csv", None) if viz else None

    # Load data; flatten val/test for image/kl metrics
    with rstatus("[cyan]Loading data"):
        train, val, test = load_data(ds)
        if getattr(val, "ndim", None) == 3:
            val = val.reshape(-1, val.shape[-1])
        if getattr(test, "ndim", None) == 3:
            test = test.reshape(-1, test.shape[-1])

    rlog(
        f"[shapes] train={getattr(train, 'shape', None)} | val={getattr(val, 'shape', None)} | test={getattr(test, 'shape', None)}"
    )

    # Restore model
    with rstatus("[cyan]Restoring checkpoint"):
        model = TimeGAN(mod, train, val, test, load_weights=True)

    # Output directory
    out_dir.mkdir(parents=True, exist_ok=True)
    rlog(f"[init] output directory → {out_dir}")
    rlog(f"[plan] will generate {samples} synthetic sample(s)")

    # Real heatmap once
    real_png = out_dir / "real_heatmap.png"
    with rstatus("[cyan]Rendering real heatmap"):
        plot_heatmap(
            test,
            lvls=levels,
            c_map=cmap,
            used_log1p=use_log1p,
            title="Real LOB Depth",
            save_path=real_png,
            dpint=dpi,
        )

    # Accumulate metrics
    ssim_rows: List[Tuple[str, float]] = []
    kl_rows: List[Tuple[str, float, float]] = []
    temp_rows: List[Tuple[str, float]] = []
    lat_rows: List[Tuple[str, float]] = []

    # Generate and evaluate
    for i in range(samples):
        tag = f"synthetic_{i:03d}"

        with rstatus(f"[cyan]Generating {tag}"):
            synth: NDArray = model.generate(num_rows=int(test.shape[0]))

        synth_png = out_dir / f"{tag}.png"
        plot_heatmap(
            synth,
            lvls=levels,
            c_map=cmap,
            used_log1p=use_log1p,
            title=f"Synthetic LOB Depth #{i:03d}",
            save_path=synth_png,
            dpint=dpi,
        )

        # Metrics (respect toggles)
        ssim_val = float("nan")
        if do_ssim:
            ssim_val = get_ssim(real_png, synth_png)
        ssim_rows.append((tag, ssim_val))

        kl_sp, kl_mpr = float("nan"), float("nan")
        if do_kl:
            kl_dict = get_kl_metrics(test, synth, bins=bins)
            kl_sp, kl_mpr = float(kl_dict["spread"]), float(kl_dict["midprice_returns"])
        kl_rows.append((tag, kl_sp, kl_mpr))

        temp_val = float("nan")
        if do_temp:
            temp_val = temporal_consistency(test, synth)
        temp_rows.append((tag, temp_val))

        lat_val = float("nan")
        if do_lat:
            lat_val = latent_divergence(test, synth)
        lat_rows.append((tag, lat_val))

        rlog(
            f"[metrics] {tag}  "
            f"SSIM={ssim_val:.4f} | KL(sp)={kl_sp:.4f} | KL(mpr)={kl_mpr:.4f} | "
            f"TempCorr={temp_val:.4f} | LatDist={lat_val:.4f}"
        )

    # Present + optional CSV
    _print_metrics_table(ssim_rows, kl_rows, temp_rows, lat_rows)
    _maybe_write_metrics_csv(metrics_csv, ssim_rows, kl_rows, temp_rows, lat_rows)

    rrule("[bold green]Done[/bold green]")
