"""
visualise.py — render LOBSTER depth heatmaps and compute SSIM / KL / temporal-corr / latent-divergence
for real vs synthetic sequences generated by a trained TimeGAN model.

Also supports latent-space walks decoded via Encoder→Recovery:
  - within-regime (tight spread)
  - cross-regime (tight → wide)

Example:

  python -m src.viz.visualise \
    --viz --samples 5 --out-dir ./outs/viz_run1 --cmap magma --dpi 240 --bins 128 --levels 10 \
           --walk --walk-steps 8 --walk-mode cross --walk-prefix latent_walk \
    --dataset --seq-len 128 --data-dir ./data \
              --orderbook-filename AMZN_2012-06-21_34200000_57600000_orderbook_10.csv \
    --modules --batch-size 128 --z-dim 40 --hidden-dim 64 --num-layer 3 --num-iters 25000
"""

from __future__ import annotations

from pathlib import Path
from typing import List, Tuple

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import torch
from numpy.typing import NDArray

from src.dataset import load_data
from src.helpers.args import Options
from src.helpers.constants import NUM_LEVELS as DEFAULT_LEVELS
from src.helpers.constants import OUTPUT_DIR
from src.helpers.richie import log as rlog
from src.helpers.richie import rule as rrule
from src.helpers.richie import status as rstatus
from src.helpers.utils import (
    get_kl_metrics,
    get_ssim,
    latent_divergence,
    temporal_consistency,
)
from src.modules import TimeGAN

# Optional pretty tables (graceful fallback if rich unavailable)
try:
    from rich import box
    from rich.console import Console
    from rich.table import Table

    _HAS_RICH = True
except ImportError:
    _HAS_RICH = False


# --------------------------------------------------------------------------------------
# Utilities
# --------------------------------------------------------------------------------------
def _pick_cmap(name: str):
    """Resolve a matplotlib colormap by name with fallback."""
    try:
        return plt.get_cmap(name)
    except Exception:
        rlog(f"[warn] unknown colormap '{name}', falling back to 'coolwarm'")
        return plt.get_cmap("coolwarm")


def _compute_spread_1(data_2d: NDArray) -> NDArray:
    """
    Compute best-level spread (ask_price_1 - bid_price_1) from 2D matrix [T,F]
    assuming block order [ask_p, ask_sz, bid_p, bid_sz] repeated by level.
    """
    ask1 = data_2d[:, 0]
    bid1 = data_2d[:, 2]
    return ask1 - bid1


def _find_window_by_spread(
    data_2d: NDArray,
    win_len: int,
    mode: str = "tight",
) -> int:
    """
    Return start index for a window of length win_len with minimum (tight) or maximum (wide) mean spread.
    """
    spreads = _compute_spread_1(data_2d)
    t = len(spreads)
    if t <= win_len:
        return 0
    csum = np.cumsum(np.insert(spreads, 0, 0.0))
    means = (csum[win_len:] - csum[:-win_len]) / win_len  # length T - win_len + 1
    return int(np.argmin(means) if mode == "tight" else np.argmax(means))


# --------------------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------------------
def plot_heatmap(
    data_2d: NDArray,
    *,
    lvls: int,
    cmap_: str,
    use_log1p_: bool,
    title: str,
    save_path: Path,
    dpi_: int,
) -> None:
    """
    Render a single heatmap with asks stacked above bids.
    Rows = 2*levels (top half: ask sizes 1...L, bottom half: bid sizes 1...L), columns = time.
    """
    asks = np.stack([data_2d[:, 4 * L + 1] for L in range(lvls)], axis=1)  # [T, L]
    bids = np.stack([data_2d[:, 4 * L + 3] for L in range(lvls)], axis=1)  # [T, L]

    mat = np.concatenate([asks.T, bids.T], axis=0)  # [2L, T]
    if use_log1p_:
        mat = np.log1p(mat)

    sns.set_theme(style="whitegrid")
    fig, ax = plt.subplots(figsize=(9, 6))
    sns.heatmap(mat, ax=ax, cmap=_pick_cmap(cmap_), cbar=True)
    ax.set_title(title)
    ax.set_ylabel("Levels (Top = Ask, Bottom = Bid)")
    ax.set_xlabel("Time")
    fig.tight_layout()

    save_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(save_path, dpi=dpi_, bbox_inches="tight")
    plt.close(fig)
    rlog(f"[save] heatmap → {save_path}")


def plot_walk_panel(
    steps: List[NDArray],
    *,
    lvls: int,
    cmap_: str,
    use_log1p_: bool,
    title: str,
    save_path: Path,
    dpi_: int,
) -> None:
    """
    Render a latent walk as a row of small heatmaps (asks over bids), left→right.
    """
    n = len(steps)
    sns.set_theme(style="whitegrid")
    fig, axes = plt.subplots(1, n, figsize=(3 * n, 4), squeeze=False)
    for k, step in enumerate(steps):
        asks = np.stack([step[:, 4 * L + 1] for L in range(lvls)], axis=1)
        bids = np.stack([step[:, 4 * L + 3] for L in range(lvls)], axis=1)
        mat = np.concatenate([asks.T, bids.T], axis=0)
        if use_log1p_:
            mat = np.log1p(mat)
        ax = axes[0, k]
        sns.heatmap(mat, ax=ax, cmap=_pick_cmap(cmap_), cbar=False)
        ax.set_title(f"Step {k}")
        ax.set_xticks([])
        ax.set_yticks([])
    fig.suptitle(title)
    fig.tight_layout()
    save_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(save_path, dpi=dpi_, bbox_inches="tight")
    plt.close(fig)
    rlog(f"[save] latent walk → {save_path}")


# --------------------------------------------------------------------------------------
# Metrics presentation
# --------------------------------------------------------------------------------------
def _print_metrics_table(
    ssim_rows_: List[Tuple[str, float]],
    kl_rows_: List[Tuple[str, float, float]],
    tmp_rows: List[Tuple[str, float]],
    lat_rows_: List[Tuple[str, float]],
) -> None:
    """Pretty-print metrics (SSIM, KL(spread/mpr), temporal corr, latent distance)."""
    if not ssim_rows_:
        rlog("[info] no metrics to display")
        return

    if not _HAS_RICH:
        for j in range(len(ssim_rows_)):
            rlog(
                f"{ssim_rows_[j][0]} | "
                f"SSIM={ssim_rows_[j][1]:.4f} | "
                f"KL(sp)={kl_rows_[j][1]:.4f} | KL(mpr)={kl_rows_[j][2]:.4f} | "
                f"TempCorr={tmp_rows[j][1]:.4f} | LatDist={lat_rows_[j][1]:.4f}"
            )
        return

    table = Table(
        title="Quantitative Metrics",
        header_style="bold cyan",
        box=box.SIMPLE_HEAVY,
        show_lines=False,
    )
    table.add_column("Sample")
    table.add_column("SSIM", justify="right")
    table.add_column("KL(spread)", justify="right")
    table.add_column("KL(mpr)", justify="right")
    table.add_column("TempCorr", justify="right")
    table.add_column("LatDist", justify="right")

    for j in range(len(ssim_rows_)):
        table.add_row(
            ssim_rows_[j][0],
            f"{ssim_rows_[j][1]:.4f}",
            f"{kl_rows_[j][1]:.4f}",
            f"{kl_rows_[j][2]:.4f}",
            f"{tmp_rows[j][1]:.4f}",
            f"{lat_rows_[j][1]:.4f}",
        )

    rrule()
    try:
        Console().print(table)
    except Exception:
        for j in range(len(ssim_rows_)):
            rlog(
                f"{ssim_rows_[j][0]} | "
                f"SSIM={ssim_rows_[j][1]:.4f} | "
                f"KL(sp)={kl_rows_[j][1]:.4f} | KL(mpr)={kl_rows_[j][2]:.4f} | "
                f"TempCorr={tmp_rows[j][1]:.4f} | LatDist={lat_rows_[j][1]:.4f}"
            )
    rrule()


def _maybe_write_metrics_csv(
    out_csv: Path | None,
    ssim_rows_: List[Tuple[str, float]],
    kl_rows_: List[Tuple[str, float, float]],
    tmp_rows: List[Tuple[str, float]],
    late_rows: List[Tuple[str, float]],
) -> None:
    """Optionally write a CSV with all computed metrics."""
    if not out_csv:
        return
    import csv

    out_csv.parent.mkdir(parents=True, exist_ok=True)
    with out_csv.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["sample", "ssim", "kl_spread", "kl_mpr", "temp_corr", "lat_dist"])
        for j in range(len(ssim_rows_)):
            w.writerow(
                [
                    ssim_rows_[j][0],
                    f"{ssim_rows_[j][1]:.6f}",
                    f"{kl_rows_[j][1]:.6f}",
                    f"{kl_rows_[j][2]:.6f}",
                    f"{tmp_rows[j][1]:.6f}",
                    f"{late_rows[j][1]:.6f}",
                ]
            )
    rlog(f"[save] metrics CSV → {out_csv}")


# --------------------------------------------------------------------------------------
# Latent walks (modular)
# --------------------------------------------------------------------------------------
def generate_latent_walks(
    model_: TimeGAN,
    test_: NDArray,
    *,
    seq_len: int,
    lvls: int,
    c_map: str,
    used_log1p: bool,
    dpi_: int,
    steps: int,
    out_dire: Path,
    prefix: str = "latent_walk",
) -> None:
    """
    Generate latent walks visualising smooth transitions in latent space:
      - within tight-spread regime (tight → tight2)
      - from tight- to wide-spread regime (tight → wide)
    """

    def _encode_window(start_idx: int) -> NDArray:
        """Encode a real window [seq_len, F] → latent [seq_len, d]."""
        sl = slice(start_idx, start_idx + seq_len)
        x_win = test_[sl][None, ...]  # [1, T, F]
        x_t = torch.as_tensor(x_win, dtype=torch.float32, device=model_.device)
        with torch.no_grad():
            h = model_.netE(x_t)
        return h[0].cpu().numpy()

    def _decode_latent(h_seq: NDArray) -> NDArray:
        """Decode latent [seq_len, d] → original scale [seq_len, F]."""
        h_t = torch.as_tensor(
            h_seq[None, ...], dtype=torch.float32, device=model_.device
        )
        with torch.no_grad():
            x_tilde = model_.netR(h_t)  # [1, T, F] in scaled space
        x_np = x_tilde[0].cpu().numpy().astype(np.float32)
        # inverse scale to original feature space
        x_np = model_.fmin.astype(np.float32) + x_np * (
            model_.fmax.astype(np.float32) - model_.fmin.astype(np.float32)
        )
        return x_np

    def _walk_and_plot(h0: NDArray, h1: NDArray, save_path: Path, title: str):
        """Linear interpolation between h0 and h1; decode each step with live progress."""
        alphas = np.linspace(0.0, 1.0, max(2, steps))
        decoded_windows: List[NDArray] = []
        with rstatus(f"[cyan]Interpolating latent space ({len(alphas)} steps)"):
            for idx, a in enumerate(alphas):
                hs = (1.0 - a) * h0 + a * h1
                xs = _decode_latent(hs)
                decoded_windows.append(xs)
                if (idx + 1) % 1 == 0:
                    rlog(f"[walk] step {idx + 1}/{len(alphas)}")
        plot_walk_panel(
            decoded_windows,
            lvls=lvls,
            cmap_=c_map,
            use_log1p_=used_log1p,
            title=title,
            save_path=save_path,
            dpi_=dpi_,
        )

    # choose endpoints
    tight_idx = _find_window_by_spread(test_, seq_len, mode="tight")
    wide_idx = _find_window_by_spread(test_, seq_len, mode="wide")
    tight2_idx = max(0, min(len(test_) - seq_len, tight_idx + seq_len * 5))

    rlog(f"[walk] indices: tight={tight_idx}, tight2={tight2_idx}, wide={wide_idx}")

    # encode
    ha = _encode_window(tight_idx)
    hb = _encode_window(wide_idx)
    ha2 = _encode_window(tight2_idx)

    out_dire.mkdir(parents=True, exist_ok=True)

    # cross regime
    cross_png = out_dire / f"{prefix}_tight_to_wide.png"
    _walk_and_plot(
        ha,
        hb,
        cross_png,
        "Latent walk from tight-spread to wide-spread regime: widening best-level separation and reshaping of depth",
    )

    # within tight regime
    within_png = out_dire / f"{prefix}_tight_only.png"
    _walk_and_plot(
        ha,
        ha2,
        within_png,
        "Latent walk within a tight-spread regime: intermediate windows decoded to LOB depth heatmaps",
    )


# --------------------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------------------
if __name__ == "__main__":
    rrule("[bold cyan]Heatmaps, SSIM, KL, Temporal Corr, Latent Distance[/bold cyan]")

    # Parse unified options: top-level + nested {dataset, modules, viz}
    opts = Options().parse()
    ds = opts.dataset
    mod = opts.modules
    viz = getattr(opts, "viz", None)

    # Visualization defaults if section was omitted
    samples: int = max(0, getattr(viz, "samples", 3) if viz else 3)
    out_dir: Path = (
        getattr(viz, "out_dir", Path(OUTPUT_DIR) / "viz")
        if viz
        else (Path(OUTPUT_DIR) / "viz")
    )
    bins: int = getattr(viz, "bins", 100) if viz else 100
    cmap: str = getattr(viz, "cmap", "coolwarm") if viz else "coolwarm"
    use_log1p: bool = not getattr(viz, "no_log1p", False) if viz else True
    dpi: int = getattr(viz, "dpi", 220) if viz else 220
    levels: int = (
        int(getattr(viz, "levels"))
        if (viz and getattr(viz, "levels", None) is not None)
        else int(DEFAULT_LEVELS)
    )
    do_ssim: bool = not getattr(viz, "no_ssim", False) if viz else True
    do_kl: bool = not getattr(viz, "no_kl", False) if viz else True
    do_temp: bool = not getattr(viz, "no_temp", False) if viz else True
    do_lat: bool = not getattr(viz, "no_lat", False) if viz else True
    metrics_csv: Path | None = getattr(viz, "metrics_csv", None) if viz else None

    # Latent-walk flags (if provided in VisualiseOptions)
    do_walk: bool = bool(getattr(viz, "walk", False)) if viz else False
    walk_steps: int = int(getattr(viz, "walk_steps", 8)) if viz else 8
    walk_mode: str = (
        str(getattr(viz, "walk_mode", "both")).lower() if viz else "both"
    )  # within|cross|both
    walk_prefix: str = (
        str(getattr(viz, "walk_prefix", "latent_walk")) if viz else "latent_walk"
    )

    # Load data; flatten val/test for image/kl metrics
    with rstatus("[cyan]Loading data"):
        train, val, test = load_data(ds)
        if getattr(val, "ndim", None) == 3:
            val = val.reshape(-1, val.shape[-1])
        if getattr(test, "ndim", None) == 3:
            test = test.reshape(-1, test.shape[-1])

    rlog(
        f"[shapes] train={getattr(train, 'shape', None)} | val={getattr(val, 'shape', None)} | test={getattr(test, 'shape', None)}"
    )

    # Restore model
    with rstatus("[cyan]Restoring checkpoint"):
        model = TimeGAN(mod, train, val, test, load_weights=True)

    # Output directory
    out_dir.mkdir(parents=True, exist_ok=True)
    rlog(f"[init] output directory → {out_dir}")
    rlog(f"[plan] will generate {samples} synthetic sample(s)")

    # Real heatmap once
    real_png = out_dir / "real_heatmap.png"
    with rstatus("[cyan]Rendering real heatmap"):
        plot_heatmap(
            test,
            lvls=levels,
            cmap_=cmap,
            use_log1p_=use_log1p,
            title="Real LOB Depth",
            save_path=real_png,
            dpi_=dpi,
        )

    # Accumulate metrics
    ssim_rows: List[Tuple[str, float]] = []
    kl_rows: List[Tuple[str, float, float]] = []
    temp_rows: List[Tuple[str, float]] = []
    lat_rows: List[Tuple[str, float]] = []

    # Generate and evaluate synthetic samples
    for i in range(samples):
        tag = f"synthetic_{i:03d}"

        with rstatus(f"[cyan]Generating {tag}"):
            synth: NDArray = model.generate(num_rows=int(test.shape[0]))

        synth_png = out_dir / f"{tag}.png"
        plot_heatmap(
            synth,
            lvls=levels,
            cmap_=cmap,
            use_log1p_=use_log1p,
            title=f"Synthetic LOB Depth #{i:03d}",
            save_path=synth_png,
            dpi_=dpi,
        )

        # Metrics (respect toggles)
        ssim_val = float("nan")
        if do_ssim:
            ssim_val = get_ssim(real_png, synth_png)
        ssim_rows.append((tag, ssim_val))

        kl_sp, kl_mpr = float("nan"), float("nan")
        if do_kl:
            kl_dict = get_kl_metrics(test, synth, bins=bins)
            kl_sp, kl_mpr = float(kl_dict["spread"]), float(kl_dict["midprice_returns"])
        kl_rows.append((tag, kl_sp, kl_mpr))

        temp_val = float("nan")
        if do_temp:
            temp_val = temporal_consistency(test, synth)
        temp_rows.append((tag, temp_val))

        lat_val = float("nan")
        if do_lat:
            lat_val = latent_divergence(test, synth)
        lat_rows.append((tag, lat_val))

        rlog(
            f"[metrics] {tag}  SSIM={ssim_val:.4f} | KL(sp)={kl_sp:.4f} | KL(mpr)={kl_mpr:.4f} | TempCorr={temp_val:.4f} | LatDist={lat_val:.4f}"
        )

    # Present + optional CSV
    _print_metrics_table(ssim_rows, kl_rows, temp_rows, lat_rows)
    _maybe_write_metrics_csv(metrics_csv, ssim_rows, kl_rows, temp_rows, lat_rows)

    # Latent walks
    if do_walk:
        rlog(f"[walk] mode={walk_mode} steps={walk_steps} prefix={walk_prefix}")
        if walk_mode in ("both", "cross", "within"):
            generate_latent_walks(
                model,
                test,
                seq_len=mod.seq_len,
                lvls=levels,
                c_map=cmap,
                used_log1p=use_log1p,
                dpi_=dpi,
                steps=walk_steps,
                out_dire=out_dir,
                prefix=walk_prefix,
            )
        else:
            rlog(f"[warn] unknown walk_mode '{walk_mode}', skipping walks")

    rrule("[bold green]Done[/bold green]")
